name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: iOS build
      uses: yukiarrr/ios-build-action@v1.4.0
      with:
        workspace-path: "./LearningSwift.xcworkspace"
        scheme: "LearningSwift"
        configuration: "Debug"
