name: Swift

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
    - uses: actions/checkout@v2
    
    - name: Set Gems
      run: |
        gem install bundler
        bundle install
        
    - name: Bundle Install
      run: |
         bundle install
      
    - name: Brew install
      run: |
        brew bundle
      
    - name: XcodeGen
      run: |
        xcodegen generate
      
    - name: iOS build
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: "build"
