name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: XcodeGen
    - uses: xavierLowmiller/xcodegen-action@1.1.2
    
    - name: iOS build
      uses: maierj/fastlane-action@v2.0.1
      with:
        lane: "build"
